workflow:
  retryMax: 5
  retryDelta: 0.01
logging:
  level:
    xyz.majexh.workflow: debug
server:
  port: 8081
spring:
  jpa:
    database: mysql
  profiles:
    active: dev
jwt:
  # token的过期时间为5天
  expirationTime: 432000000
  # jwt秘钥
  secret: 'test'

